[build]
  base = "client"
  command = "npm run build"
  publish = "build"

# Handle SPA routing by redirecting all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 